SELECT CATEGORY, PRICE AS MAX(PRICE), PRODUCT_NAME
-- GROUP BY 쓸때는 RANK, 아닐 떈 ROWNUM 쓰면 된다
FROM (SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC)) AS ROW_RANK
WHERE ROW_RANK=1
ORDER PRICE DESC;