-- 1. 같은 테이블 JOIN하면 공통되는 게 있는 것만 조회됨
-- 2. WHERE 원래 날짜는 후날짜보다 작아야함 
-- 3. HAVING 여러번 구매한 건 1과 같거나 커야함
-- 4. ORDER BY 

--같은 테이블 JOIN 안해봄/하면서 익숙해지자.
SELECT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID
WHERE A.SALES_DATE < B.SALES_DATE
GROUP BY A.USER_ID, A.PRODUCT_ID
HAVING COUNT(*) >= 1
ORDER BY A.USER_ID, A.PRODUCT_ID DESC;