-- 1. A RIGHT OUTER JOIN B ON A.=B.
-- 2. 컬럼명 IS NULL
-- 3. ORDER BY 필요

SELECT B.ANIMAL_ID, B.NAME
FROM ANIMAL_INS A RIGHT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE A.ANIMAL_ID IS NULL
--ORDER BY 안함/B.ANIMAL_ID를 기준으로 ORDER BY 힘
ORDER BY B.ANIMAL_ID;