SELECT A.PRODUCT_CODE, A.PRICE*SUM(B.SALES_AMOUNT) AS SALES
FROM PRODUCT A JOIN OFFLINE_SALE B ON A.PRODUCT_ID=B.PRODUCT_ID
--ORACLE에선 SELECT에 있는 컬럼명들은 전부 GROUP BY에 적어야한다
GROUP BY A.PRODUCT_CODE, A.PRICE
ORDER BY SALES DESC, PRODUCT_CODE;