SELECT 
    HISTORY_ID,
    CAR_ID,
    --TO_CHAR로 년도-달-일만 표시하게 해야함
    TO_CHAR(START_DATE, 'YYYY-MM-DD') AS START_DATE, 
    TO_CHAR(END_DATE, 'YYYY-MM-DD') AS END_DATE,
    --날짜기 때문이고 빼기연산 후에는 +1을 해줘야 함
	CASE WHEN (END_DATE-START_DATE)+1 >= 30 THEN '장기 대여'
    ELSE '단기 대여' END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE TO_CHAR(START_DATE, 'YYYY-MM')='2022-09'
ORDER BY HISTORY_ID DESC;