SELECT NAME, DATETIME
FROM 
    (SELECT NAME, DATETIME, ROW_NUMBER() OVER (ORDER BY DATETIME) RN
     FROM ANIMAL_INS 
     WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)) A
WHERE RN <= 3;