SELECT ANIMAL_ID, NAME
--TO_DATE 대신 MONTHS_BETWEEN을 사용하면 날짜까지 굳이필요없는 계산을 원활하게 할수 있다다
FROM (SELECT A.ANIMAL_ID, A.NAME, MONTHS_BETWEEN(B.DATETIME,A.DATETIME) RN 
      FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON A.ANIMAL_ID=B.ANIMAL_ID
      ORDER BY RN DESC) C
--ORACLE 내부함수에는 아주 쓸만한 순번 매기기 함수 ROW_NUM이 있다.
WHERE ROWNUM < 3;